Mosaico/relevant smart ads
KSF-Media/affresco pull request #1015
Opened 2022-04-06 07:44 UTC by danielrlc

2022-04-06 08:10 UTC, danielrlc commented
@kaol Quite likely my PureScript code isn't optimal, so I'd welcome suggested improvements. I'm hoping it's fairly clear what I'm trying to achieve in this PR. Please let me know if not.

2022-04-06 08:57 UTC, kaol requested changes
Just one comment about how to use case statements.

2022-04-06 08:57 UTC, kaol commented on apps/mosaico/src/Ads/Ad.purs
> +      render { state: { gamId: Nothing, isLazy: Nothing }} = mempty
We can avoid this repetition. Remove these and instead add `render _ = mempty` after the `Just ... Just ...` case.

2022-04-06 13:49 UTC, joakimekroos approved these changes

2022-04-07 12:56 UTC, kaol approved these changes

2022-04-08 07:03 UTC, merged