Add alt text to list images and advertorial blurbs
KSF-Media/affresco pull request #1219
Opened 2022-06-14 07:18 UTC by kaol

2022-06-14 09:23 UTC, MicciKarkia approved these changes

2022-06-14 11:18 UTC, mrskug requested changes

2022-06-14 11:19 UTC, mrskug commented on apps/mosaico/src/Mosaico/Frontpage.purs
> +                                    ((_ <> "&function=hardcrop&width=200&height=200&q=90") <<< _.url) img
should be safe to remove as the frontpage only contains aptoma articles afaik

2022-06-14 11:49 UTC, kaol commented on apps/mosaico/src/Mosaico/Frontpage.purs
> +                                    ((_ <> "&function=hardcrop&width=200&height=200&q=90") <<< _.url) img
The module is named confusingly but this same list component is used for search results as well so it could have imengine hosted images as well.

2022-06-15 11:57 UTC, kaol commented on apps/mosaico/src/Mosaico/Frontpage.purs
> +                                    ((_ <> "&function=hardcrop&width=200&height=200&q=90") <<< _.url) img
I updated it to check the URL and to apply the hardcrop params only if URL matches with imengine.

2022-06-15 12:04 UTC, mrskug approved these changes

2022-06-27 08:50 UTC, merged