Remove hbl365 app
KSF-Media/affresco pull request #1464
Opened 2023-08-22 11:49 UTC by MicciKarkia

2023-08-22 15:25 UTC, jllang approved these changes

2023-08-22 15:31 UTC, jllang requested changes
I still find these mentionings of HBL 365 in this branch (by running `git grep -n "[hH][bB][lL].*365"`):
```
.github/workflows/previews.yml:51:      - name: Setup build cache for HBL365
.github/workflows/previews.yml:54:          key: "${{ runner.os }}-hbl365-${{ hashFiles('apps/hbl365/yarn.lock')}}"
.github/workflows/previews.yml:56:            apps/hbl365/.spago
.github/workflows/previews.yml:57:            apps/hbl365/output
.github/workflows/previews.yml:79:      - name: Build HBL365
.github/workflows/previews.yml:81:            ruby deploy.rb hbl365
.github/workflows/previews.yml:82:            cp -R apps/hbl365/dist build/hbl365
.github/workflows/previews.yml:112:      - name: Upload HBL365
.github/workflows/previews.yml:116:          destination: "deploy-previews/${{ github.sha }}/hbl365"
.github/workflows/previews.yml:118:          path: build/hbl365
.github/workflows/previews.yml:142:            - [HBL365](https://deploy-previews.ksfmedia.fi/${{ github.sha }}/hbl365/index.html)
.github/workflows/production.yml:61:      - name: Setup build cache for HBL365
.github/workflows/production.yml:64:          key: "${{ runner.os }}-hbl365-${{ hashFiles('apps/hbl365/yarn.lock')}}"
.github/workflows/production.yml:66:            apps/hbl365/.spago
.github/workflows/production.yml:67:            apps/hbl365/output
.github/workflows/production.yml:89:      - name: Build HBL365
.github/workflows/production.yml:91:            ruby deploy.rb hbl365
.github/workflows/production.yml:92:            cp -R apps/hbl365/dist build/hbl365
.github/workflows/production.yml:122:      - name: Upload HBL365
.github/workflows/production.yml:126:          destination: ksf-frontends/hbl365
.github/workflows/production.yml:128:          path: build/hbl365
apps/prenumerera/src/Package/Description.purs:39:          , Tuple "E-tidningar" "Papperstidningar digitalt i appen HBL 365 och på webben (HBL, VN & ÖN)"
apps/prenumerera/src/Package/Description.purs:58:          , Tuple "E-tidningar" "Papperstidningar digitalt i appen HBL 365 och på webben (HBL, VN & ÖN)"
apps/prenumerera/src/Package/Description.purs:77:          , Tuple "E-tidningar" "Papperstidningar digitalt i appen HBL 365 och på webben (HBL, VN & ÖN)"
apps/prenumerera/src/Package/Description.purs:114:          , Tuple "E-tidningen" "Papperstidningen digitalt i appen HBL 365 och på webben (ÖN)"
apps/prenumerera/src/Package/Description.purs:133:          , Tuple "E-tidningar" "Papperstidningar digitalt i appen HBL 365 och på webben (ÖN, HBL & VN)"
apps/prenumerera/src/Package/Description.purs:152:          , Tuple "E-tidningen" "Papperstidningen digitalt i appen HBL 365 och på webben (ÖN)"
apps/prenumerera/src/Package/Description.purs:171:          , Tuple "E-tidningen" "Papperstidningen digitalt i appen HBL 365 och på webben (VN)"
apps/prenumerera/src/Package/Description.purs:190:          , Tuple "E-tidningar" "Papperstidningar digitalt i appen HBL 365 och på webben (VN, HBL & ÖN)"
apps/prenumerera/src/Package/Description.purs:209:          , Tuple "E-tidningen" "Papperstidningen digitalt i appen HBL 365 och på webben (VN)"
apps/prenumerera/src/Package/Description.purs:234:  , "HBL 365" /\
apps/prenumerera/src/Package/Description.purs:243:          , Tuple "E-tidningar" "Papperstidningar digitalt i appen HBL 365 och på webben (HBL, VN & ÖN)"
apps/prenumerera/src/Package/Description.purs:250:      , image: "HBL365365.png"
apps/prenumerera/src/Package/Description.purs:251:      , packageGroup: "HBL 365"
apps/vetrina-test/src/Main.purs:41:        , accessEntitlements: Set.fromFoldable ["hbl-365", "hbl-web"]
apps/vetrina-test/test/Main.purs:120:  log "Selecting HBL 365"
apps/vetrina-test/test/Main.purs:121:  let selector365 = Chrome.Selector "#HBL\\ 365"
ci/apps.dhall:58:          , name = "HBL365"
ci/apps.dhall:59:          , buildDir = "hbl365"
ci/apps.dhall:60:          , deployDir = "hbl365"
ci/apps.dhall:64:              apps/hbl365/.spago
ci/apps.dhall:65:              apps/hbl365/output
less/HBL365.less:335:#what-is-hbl-365 {
less/prenumerera/ksf-block-hbl365-promo.less:1:.ksf-block-hbl365-promo {
less/prenumerera/ksf-home.less:68:.ksf-block-hbl365{
less/prenumerera/ksf-home.less:80:    .hbl365-form{
less/prenumerera/main.less:16:@import 'ksf-block-hbl365-promo.less';
packages/vetrina/src/Vetrina/Products/Premium.purs:86:        , description: "Papperstidningen digitalt i appen HBL 365 och på webben (VN)"
packages/vetrina/src/Vetrina/Products/Premium.purs:129:        , description: "Papperstidningen digitalt i appen HBL 365 och på webben (ÖN)"
```
I think at least those `.yaml` and `.dhall` files should be updated. I'm not sure about the `.less` files. Maybe those lines could also be removed.

2023-08-23 11:36 UTC, MicciKarkia commented
> I still find these mentionings of HBL 365 in this branch (by running `git grep -n "[hH][bB][lL].*365"`):
> 
> ```
> .github/workflows/previews.yml:51:      - name: Setup build cache for HBL365
> .github/workflows/previews.yml:54:          key: "${{ runner.os }}-hbl365-${{ hashFiles('apps/hbl365/yarn.lock')}}"
> .github/workflows/previews.yml:56:            apps/hbl365/.spago
> .github/workflows/previews.yml:57:            apps/hbl365/output
> .github/workflows/previews.yml:79:      - name: Build HBL365
> .github/workflows/previews.yml:81:            ruby deploy.rb hbl365
> .github/workflows/previews.yml:82:            cp -R apps/hbl365/dist build/hbl365
> .github/workflows/previews.yml:112:      - name: Upload HBL365
> .github/workflows/previews.yml:116:          destination: "deploy-previews/${{ github.sha }}/hbl365"
> .github/workflows/previews.yml:118:          path: build/hbl365
> .github/workflows/previews.yml:142:            - [HBL365](https://deploy-previews.ksfmedia.fi/${{ github.sha }}/hbl365/index.html)
> .github/workflows/production.yml:61:      - name: Setup build cache for HBL365
> .github/workflows/production.yml:64:          key: "${{ runner.os }}-hbl365-${{ hashFiles('apps/hbl365/yarn.lock')}}"
> .github/workflows/production.yml:66:            apps/hbl365/.spago
> .github/workflows/production.yml:67:            apps/hbl365/output
> .github/workflows/production.yml:89:      - name: Build HBL365
> .github/workflows/production.yml:91:            ruby deploy.rb hbl365
> .github/workflows/production.yml:92:            cp -R apps/hbl365/dist build/hbl365
> .github/workflows/production.yml:122:      - name: Upload HBL365
> .github/workflows/production.yml:126:          destination: ksf-frontends/hbl365
> .github/workflows/production.yml:128:          path: build/hbl365
> apps/prenumerera/src/Package/Description.purs:39:          , Tuple "E-tidningar" "Papperstidningar digitalt i appen HBL 365 och på webben (HBL, VN & ÖN)"
> apps/prenumerera/src/Package/Description.purs:58:          , Tuple "E-tidningar" "Papperstidningar digitalt i appen HBL 365 och på webben (HBL, VN & ÖN)"
> apps/prenumerera/src/Package/Description.purs:77:          , Tuple "E-tidningar" "Papperstidningar digitalt i appen HBL 365 och på webben (HBL, VN & ÖN)"
> apps/prenumerera/src/Package/Description.purs:114:          , Tuple "E-tidningen" "Papperstidningen digitalt i appen HBL 365 och på webben (ÖN)"
> apps/prenumerera/src/Package/Description.purs:133:          , Tuple "E-tidningar" "Papperstidningar digitalt i appen HBL 365 och på webben (ÖN, HBL & VN)"
> apps/prenumerera/src/Package/Description.purs:152:          , Tuple "E-tidningen" "Papperstidningen digitalt i appen HBL 365 och på webben (ÖN)"
> apps/prenumerera/src/Package/Description.purs:171:          , Tuple "E-tidningen" "Papperstidningen digitalt i appen HBL 365 och på webben (VN)"
> apps/prenumerera/src/Package/Description.purs:190:          , Tuple "E-tidningar" "Papperstidningar digitalt i appen HBL 365 och på webben (VN, HBL & ÖN)"
> apps/prenumerera/src/Package/Description.purs:209:          , Tuple "E-tidningen" "Papperstidningen digitalt i appen HBL 365 och på webben (VN)"
> apps/prenumerera/src/Package/Description.purs:234:  , "HBL 365" /\
> apps/prenumerera/src/Package/Description.purs:243:          , Tuple "E-tidningar" "Papperstidningar digitalt i appen HBL 365 och på webben (HBL, VN & ÖN)"
> apps/prenumerera/src/Package/Description.purs:250:      , image: "HBL365365.png"
> apps/prenumerera/src/Package/Description.purs:251:      , packageGroup: "HBL 365"
> apps/vetrina-test/src/Main.purs:41:        , accessEntitlements: Set.fromFoldable ["hbl-365", "hbl-web"]
> apps/vetrina-test/test/Main.purs:120:  log "Selecting HBL 365"
> apps/vetrina-test/test/Main.purs:121:  let selector365 = Chrome.Selector "#HBL\\ 365"
> ci/apps.dhall:58:          , name = "HBL365"
> ci/apps.dhall:59:          , buildDir = "hbl365"
> ci/apps.dhall:60:          , deployDir = "hbl365"
> ci/apps.dhall:64:              apps/hbl365/.spago
> ci/apps.dhall:65:              apps/hbl365/output
> less/HBL365.less:335:#what-is-hbl-365 {
> less/prenumerera/ksf-block-hbl365-promo.less:1:.ksf-block-hbl365-promo {
> less/prenumerera/ksf-home.less:68:.ksf-block-hbl365{
> less/prenumerera/ksf-home.less:80:    .hbl365-form{
> less/prenumerera/main.less:16:@import 'ksf-block-hbl365-promo.less';
> packages/vetrina/src/Vetrina/Products/Premium.purs:86:        , description: "Papperstidningen digitalt i appen HBL 365 och på webben (VN)"
> packages/vetrina/src/Vetrina/Products/Premium.purs:129:        , description: "Papperstidningen digitalt i appen HBL 365 och på webben (ÖN)"
> ```
> 
> I think at least those `.yml` and `.dhall` files should be updated. I'm not sure about the `.less` files. Maybe those lines could also be removed.

@mrskug updated the `.yml` and `.dhall` files and I think I'll leave the less files as we are moving to Tailwind anyway

2023-08-23 11:37 UTC, jllang approved these changes

2023-08-23 13:02 UTC, merged