Patch/frontpage html
KSF-Media/affresco pull request #868
Opened 2021-12-14 12:16 UTC by ae-mo

Closes #841.

2021-12-14 12:52 UTC, ae-mo commented on apps/mosaico/package.json
> +    "build": "parcel build ./static/* -d dist/client && parcel watch web/index.html -d dist/client --public-url /assets"
Sorry about this, gonna revert

2021-12-23 08:34 UTC, kaol requested changes

2021-12-23 08:34 UTC, kaol commented on apps/mosaico/src/Main.purs
> +getFrontPage paper category = do
Remove trailing white space.

2021-12-23 08:34 UTC, kaol commented on apps/mosaico/src/Mosaico.purs
> +          case feedContentType of
Remove trailing white space.

2021-12-23 08:34 UTC, kaol commented on apps/mosaico/src/Mosaico.purs
> +    frontpage frontpageArticles =
Remove trailing white space.

2021-12-23 08:34 UTC, kaol commented on apps/mosaico/src/Mosaico/Frontpage.purs
> +    , children: maybe
Remove trailing white space.

2021-12-23 08:34 UTC, kaol commented on apps/mosaico/src/Mosaico/Frontpage.purs
> +            Html html        -> [ state.htmlRendererComponent
Remove trailing white space.

2021-12-23 08:34 UTC, kaol commented on apps/mosaico/src/Mosaico/Frontpage.purs
> +
Remove white space.

2021-12-23 08:34 UTC, kaol commented on packages/components/src/HtmlRenderer/Models.js
> +// html-to-react uses htmlparser to parse input and each
Remove trailing white space.

2021-12-23 08:34 UTC, kaol commented on packages/components/src/HtmlRenderer/Models.js
> +exports.getAttribsImpl = (node) => {
Remove trailing white space from this line and from the rest of exports in this file too.

2021-12-23 08:34 UTC, kaol commented on packages/components/src/HtmlRenderer/Models.purs
> +-- | This type of hook is to replace the children of
Remove trailing white space.

2021-12-23 08:34 UTC, kaol commented on packages/components/src/HtmlRenderer/Models.purs
> +type ReplacingHookRecord =
Remove trailing white space.

2021-12-23 08:34 UTC, kaol commented on packages/components/src/HtmlRenderer/Models.purs
> +  toGenericHook (ReplacingHook { shouldProcessNode, processNode }) =
Remove trailing white space.

2021-12-23 08:34 UTC, kaol commented on packages/components/src/HtmlRenderer/Models.purs
> +  toGenericHook (ModifyingHook { shouldProcessNode, processNode }) =
Remove trailing white space.

2021-12-23 08:34 UTC, kaol commented on packages/components/src/HtmlRenderer/Models.purs
> +  , onclick           :: Maybe String
Remove trailing white space.

2021-12-23 08:34 UTC, kaol commented on packages/components/src/Lettera.purs
> +  }
Remove trailing white space.

2021-12-23 08:34 UTC, kaol commented on packages/components/src/Lettera.purs
> +    Left err ->
Remove trailing white space.

2021-12-23 08:34 UTC, kaol commented on apps/mosaico/src/Main.purs
> +getFrontPage :: Paper -> String -> Aff ArticleFeed
We've used frontpage as "Frontpage" in other camel cased contexts, like in "FrontpageFeed". Let's stick to the same convention with the new names that this PR introduces, so this function would be `getFrontpage`. The same goes for other FrontPages.

2021-12-23 08:34 UTC, kaol commented on packages/components/src/HtmlRenderer.purs
> +htmlRendererComponent :: Component Props
Let's just do this as pure `render` function. A component with no state is really an antipattern with React Hooks, this only adds complexity for no benefit.

2021-12-23 09:26 UTC, kaol approved these changes

2021-12-23 09:40 UTC, merged